# Docs: https://docs.statusfy.co/config
title = "KScout Status"
description = "Overview of all KScout systems"
baseUrl = "https://status.kscout.io"
serviceWorker = true
manifest = true

[theme]
[theme.links.en]
contact = "mailto:nhuppert@redhat.com"
support = "mailto:nhuppert@redhat.com"
home = "https://kscout.io"

[notifications]
[notifications.support]
en = "mailto:nhuppert@redhat.com"

[content]
frontMatterFormat = "yaml"
systems = [
	"dns",
	"website",
	"serverless-registry-api",
	"chat-bot-api",
	"slack-chat-bot-api",
	"chat-bot-training-data",
	"status-page",
	"observe",
	"serverless-apps"
]
